In [1]:
lapp_id_no = 17

In [2]:
import numpy as np                        # Numerical Python package
import tabula                             # PDF table extra package
import numpy as np
import pandas as pd
import os
import re,string
import operator as op
import sys
import tabula
from dateutil.parser import parse # Fixing the dates
if not sys.warnoptions:
    import warnings
    warnings.simplefilter("ignore")
bank_data=pd.read_csv("C:/Users/VSK/Downloads/bank_data.csv")
lapp_id=list(bank_data["lapp_id"])
bank=list(bank_data["bank"])

In [3]:
file_name=lapp_id[lapp_id_no]
bank_name=bank[lapp_id_no]
#result_read=[]
#result_tansform=[]
#result3_salary=[]
print(file_name)
print(bank_name)
pdf_file = 'C:/Users/VSK/Download/Bank statement/'+file_name+'.pdf'
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
df = tabula.read_pdf(pdf_file, pages = 'all',multiple_tables=True)
df_list=df
col_list=["Description","Narration","Remarks","Particulars","DESCRIPTION","Description","Description","PARTICULARS",
                  "Transaction Details","Narration","NARRATION","PERTICULERS","Details of transaction","ransaction Remarks",
                 "Transaction\rParticulars","Transaction Description","ransaction Remarks","Account Description","NARATION",
                 "Narration Chq/Ref No","Deposits","Amount (Rs.)","Credit","CREDIT","Deposit Amt.","DEPOSIT","Deposit",
          "Deposit Amount\r(INR )","Amount","Deposit Amt","Type","Deposit Balance","WithDrawal","Value",
              "Credit (Rs.)","Withdrawal Amt. Deposit Amt.","Deposit Amount\r(INR )","Credit(Rs)","Withdrawals Deposits",
               "Cr Amount","Withdrawal (Dr)/","Withdrawal Amt.","Withdrawal","Withdrawal","DEBIT","Withdrawals","Debit",
          "Withdrawal (Dr)" ,"Withdrawal Amt. Deposit Amt.","Withdrawal (Dr)/","Withdrawal Amount\r(INR )","Debit (Rs.)",
          "Debit(Rs)","WITHDRAWALS","Withdrawal INR","Withdrawal Amt","Amount","Withdrawal Amount","Withdrawals Deposits",
             "Dr Amount", "Balance","Closing Balance","BALANCE","Running Balance","BALANCE","Balance (INR )","Amount","MODE**",
                "Running","Balance(Rs)","Total Amount\rDr/Cr","Date","date","Transaction","Txn","Transaction Date","Debit/Credit",
          "Transaction date", "Txn Date", "Tran Date","Balance (?)","Branch","Cheque No","Chq./Ref.","Entry Date",'Cheque',
             "TRANSACTION\rDATE","Trans Date","Tran Date","DATE","Post Date","Value\rDate","Date (Value\rDate)","Tran Date",
             "Txn dt", "Txn Dt","Value Date" ,'Chq./Ref.No.','Value Dt',"Chq\rNo.","Transaction Description","Total Amount\rDr/Cr",
          "Debit (Rs.)","Credit (Rs.)","Balance (Rs.)","Dr Amount","Cr Amount","Instruments","Total Amou"]

date_list = ["Date","date","Transaction","Txn","Transaction Date","Transaction date", "Txn Date", "Tran Date","Date",
             "TRANSACTION\rDATE","Trans Date","Tran Date","DATE","Post Date","Value\rDate","Date (Value\rDate)",
             "Txn dt", "Txn Dt","Value Date"]
narration_list = ["Description","Narration","Remarks","Particulars","DESCRIPTION","Description","Description","PARTICULARS",
                  "Transaction Details","Narration","NARRATION","PERTICULERS","Details of transaction","ransaction Remarks",
                 "Transaction\rParticulars","Transaction Description","ransaction Remarks","Account Description","NARATION",
                 "Narration Chq/Ref No"]

credit_list = ["Deposits","Amount (Rs.)","Credit","CREDIT","Deposit Amt.","DEPOSIT","Deposit","Deposit Amount\r(INR )","Amount",
              "Credit (Rs.)","Withdrawal Amt. Deposit Amt.","Deposit Amount\r(INR )","Credit(Rs)","Withdrawals Deposits",
               "Cr Amount","Withdrawal (Dr)/","DEPOSITS","WITHDRAWALS"]

debit_list = ["Withdrawal Amt.","Withdrawal","Withdrawal","DEBIT","Withdrawals","Debit","Withdrawal (Dr)"
              ,"Withdrawal Amt. Deposit Amt.","Withdrawal (Dr)/","Withdrawal Amount\r(INR )","Debit (Rs.)","Debit(Rs)",
             "WITHDRAWALS","Withdrawal INR","Withdrawal Amt","Amount","Withdrawal Amount","Withdrawals Deposits","WithDrawal",
             "Dr Amount"]


balance_list = ["Balance","Closing Balance","BALANCE","Running Balance","BALANCE","Balance (INR )","Amount",
                "Running","Balance(Rs)","Total Amount\rDr/Cr"]

test_data=df_list[0]
col_len=test_data.shape[1]
tab_cols=test_data.columns
table_columns=[]
row_index=[]
for elem in range(len(tab_cols)):
    if tab_cols[elem] in col_list:
        col_name=tab_cols[elem]
        table_columns.append(col_name)
    else:
        table_columns.append("Unknown_column")
uc_count=op.countOf(table_columns, "Unknown_column")
print(uc_count)
if uc_count>=3 or len(table_columns)<=3:
    for row_ind in range(col_len-1):
        test_list=list(test_data[tab_cols[row_ind]])
        for i in range(len(col_list)):
            col_el=col_list[i]
            if col_el in test_list:
                row_inde=test_list.index(col_el)
                row_index.append(row_inde)
    if len(row_index)==0:
        print("Summary_problem")
        if len(df_list)<= 4:
            lst_no=0
        else:
            lst_no=4
        data1=df_list[1]
        data2=df_list[2]
        data3=df_list[lst_no]
        data1_columns=[]
        data2_columns=[]
        data3_columns=[]
        page_data1=data1.values.tolist()
        page_data2=data2.values.tolist()
        page_data3=data3.values.tolist()
        data1_cols=data1.columns
        data2_cols=data2.columns
        data3_cols=data3.columns
        for elem in range(len(data1_cols)):
            if data1_cols[elem] in col_list:
                col_name=data1_cols[elem]
                data1_columns.append(col_name)
            else:
                data1_columns.append("Unknown_column")
        for elem in range(len(data2_cols)):
            if data2_cols[elem] in col_list:
                col_name=data2_cols[elem]
                data2_columns.append(col_name)
            else:
                data1_columns.append("Unknown_column")
        for elem in range(len(data3_cols)):
            if data3_cols[elem] in col_list:
                col_name=data3_cols[elem]
                data3_columns.append(col_name)
            else:
                data3_columns.append("Unknown_column")            
        data1_count=op.countOf(data1_columns, "Unknown_column")
        data2_count=op.countOf(data2_columns, "Unknown_column")
        data3_count=op.countOf(data3_columns, "Unknown_column")
        data_uc_count=[data1_count,data2_count,data3_count]
        min_uc_index = data_uc_count.index(min(data_uc_count))
        dict_cols={0:data1_columns,1:data2_columns,2:data3_columns}
        dict_data={0:data1,1:data2,2:data3}
        data_tab_cols=dict_cols[min_uc_index]
        data_first=dict_data[min_uc_index]
        pdf_data=[]
        page_data0=data_first.values.tolist()
        pdf_data=pdf_data + page_data0
        pdf_data=pdf_data + page_data1
        pdf_data=pdf_data + page_data2
        pdf_data=pdf_data + page_data3
        for ls in range(len(df_list)):
            page_data=df[ls].values.tolist()
            pdf_data=pdf_data+page_data
        data1_pdf=pd.DataFrame(pdf_data)
        repete=data1_pdf.shape[1]-len(data_tab_cols)
        for add in range(repete):
            data_tab_cols.append('column_added')
        pdf_data=pd.DataFrame(pdf_data,columns= data_tab_cols)
        data_pdf=pdf_data.replace(np.nan,'')
        com_table=data_pdf
        com_table1=data_pdf
    elif min(row_index)>=2:
        print("summmary Problem 2")
        test_data1=test_data.values.tolist()
        row_value=min(row_index)
        data1_col_list=test_data1[row_value]
        data2_col_list=test_data1[row_value+1]
        data_col_list=data1_col_list + data2_col_list
        columns_list=[]
        row_columns=[]
        for elem in range(len(data_col_list)):
            txt=data_col_list[elem]
            txt=str(txt)
            list_txt =list(txt.split())
            columns_list=columns_list+list_txt
        for elem in range(len(columns_list)):
            if columns_list[elem] in col_list:
                col_name=columns_list[elem]
                row_columns.append(col_name)
        data1=df_list[1]
        data1=data1.values.tolist()
        #data1=pd.DataFrame(data1,columns=row_columns)
        for lst_len in range(len(df_list)):
            page_data=df_list[lst_len]
            page_data=page_data.values.tolist()
            data1=data1+page_data
        pdf_data1=pd.DataFrame(data1)    
        repete=pdf_data1.shape[1]-len(row_columns)
        for add in range(repete):
            row_columns.append('column_added')
        pdf_data=pd.DataFrame(data1,columns=row_columns)
        pdf_data=pdf_data.replace(np.nan,'')
        com_table=pdf_data
        com_table1=pdf_data
    else:
        num_row=0
        pdf_data=[]
        pdf_data.append(list(df[num_row]))
        pdf_columns=list(df[num_row])
        for ls in range(len(df_list)-num_row):
            page_data=df[ls+num_row].values.tolist()
            pdf_data=pdf_data+page_data
        data_pdf=pd.DataFrame(pdf_data)
        data_pdf=data_pdf.replace(np.nan,'')
        repete=data_pdf.shape[1]-len(pdf_columns)
        for add in range(repete):
            pdf_columns.append('columns')
        
        data_pdf=data_pdf.rename(columns=data_pdf.iloc[0]).drop(data_pdf.index[0]) 
        data_pdf1=data_pdf.rename(columns=data_pdf.iloc[0]).drop(data_pdf.index[0])
        com_table=data_pdf
        com_table1=data_pdf1    
else:
    num_row=0
    pdf_data=[]
    pdf_data.append(list(df[num_row]))
    pdf_columns=list(df[num_row])
    for ls in range(len(df_list)-num_row):
        page_data=df[ls+num_row].values.tolist()
        pdf_data=pdf_data+page_data
    data_pdf=pd.DataFrame(pdf_data)
    data_pdf=data_pdf.replace(np.nan,'')
    repete=data_pdf.shape[1]-len(pdf_columns)
    for add in range(repete):
        pdf_columns.append('columns')
        
    data_pdf=data_pdf.rename(columns=data_pdf.iloc[0]).drop(data_pdf.index[0]) 
    data_pdf1=data_pdf.rename(columns=data_pdf.iloc[0]).drop(data_pdf.index[0])
    com_table=data_pdf
    com_table1=data_pdf1   
cols = list(com_table.columns)
cols1 = list(com_table1.columns)
#cols2 = list(com_table2.columns)
for i in range(len(cols)):
    if cols[i] in date_list:
        date=cols[i]
        date_ind=i
        print(date,date_ind)
for j in range(len(cols1)):
    if cols1[j] in date_list:
        date=cols1[j]
        date_ind=j
for k in range(len(cols)):
    if cols[k] in narration_list:
        narration=cols[k]
        nar_ind=k
        print(narration,nar_ind)
for l in range(len(cols1)):
    if cols1[l] in narration_list:
        narration=cols1[l]
        nar_ind=l
for m in range(len(cols)):
    if cols[m] in credit_list:
        credit=cols[m]
        credit_ind=m 
        print(credit,credit_ind)
for n in range(len(cols1)):
    if cols1[n] in credit_list:
        credit=cols1[n]
        credit_ind=n 
        print(credit,credit_ind)  
for dbt in range(len(cols)):
    if cols[dbt] in debit_list:
        debit=cols[dbt]
        debit_ind=dbt
        print(debit,debit_ind)
for dbt1 in range(len(cols1)):
    if cols1[dbt1] in debit_list:
        debit=cols1[dbt1]
        debit_ind=dbt1
        print(debit,debit_ind)
for blns in range(len(cols)):
    if cols[blns] in balance_list:
        balance=cols[blns]
        balance_ind=blns
        print(balance,balance_ind)
for blns1 in range(len(cols1)):
    if cols1[blns1] in balance_list:
        balance=cols1[blns1]
        balance_ind=blns1
        print(balance,balance_ind)
Transaction_date =list(com_table[cols[date_ind]])
Narration = list(com_table[cols[nar_ind]])
Deposits=list(com_table[cols[credit_ind]])
Debit = list(com_table[cols[debit_ind]])
Balance = list(com_table[cols[balance_ind]])
data4=pd.DataFrame(Transaction_date,columns=["Transaction Date"])
data5 = pd.DataFrame(Narration,columns=["Narration"])
data6 = pd.DataFrame(Deposits,columns=["Credit"])
data7 = pd.DataFrame(Debit,columns=["Debit"])
data8 = pd.DataFrame(Balance, columns= ["Balance"])
data=data4.join(data5)
data=data.join(data6)
data=data.join(data7)
data =data.join(data8)
data=data.replace(np.nan,'')
axis_list=["axis-bank","Axis Bank  India","Axis Bank  India","AXIS (UTI) Bank","Axis Bank India","Axis Bank, India",
                   "Axis Ban","Axis Bank","Axis Bank Ltd","Axis Bank Ltd.","Axis Bank ","Axis","axis","AXIS"]

if bank_name in axis_list:
    for ele in range(len(Narration)-1):
        if Transaction_date[ele] == '' and Balance [ele]== '':
            Narration[ele+1]=str(Narration[ele])+str(Narration[ele+1])
else:
    for ele in range(len(Narration)):
        if Transaction_date[ele] == '':
            Narration[ele-1]=str(Narration[ele-1])+str(Narration[ele])
Transaction_date=pd.DataFrame(Transaction_date,columns=["Transaction Date"])
Narration= pd.DataFrame(Narration,columns=["Narration"])
Deposits = pd.DataFrame(Deposits,columns=["Credit"])
Debit = pd.DataFrame(Debit,columns=["Debit"])
Balance = pd.DataFrame(Balance,columns=["Balance"])
data=Transaction_date.join(Narration)
data=data.join(Deposits)
data=data.join(Debit)
data=data.join(Balance)
#data=data.replace('',np.nan)
#data=data.dropna()
txn_date = list(data["Transaction Date"])
cr_list=list(data["Credit"])
dr_list=list(data["Debit"])
bls_list=list(data["Balance"])
row_index=[]
for row_num in range(len(data["Narration"])):
    if txn_date[row_num]== '':
        a=row_num
        row_index.append(a)
    elif cr_list[row_num]== '' and dr_list[row_num]== '' and bls_list=='' :
        b=row_num
        row_index.append(b)
unique_row_index = []
for x in range(len(row_index)):
    if row_index[x] not in unique_row_index:
        row_ind=row_index[x]
        unique_row_index.append(row_ind)
data=data.drop(unique_row_index,axis=0)
salary1 = data[data["Narration"].str.contains("SALARY")]
salary2 = data[data["Narration"].str.contains("Salary")]
sala_cr= data[data["Narration"].str.contains("CREDIT")]
salary3 = data[data["Narration"].str.contains("salary")]
sal_ac = data[data["Narration"].str.contains("SAL")]
sal_fl = data[data["Narration"].str.contains("Sal")]
#sal_al = data[data["Narration"].str.contains("sal")]
NEFT = data[data["Narration"].str.contains("NEFT")]
IMPS = data[data["Narration"].str.contains("IMPS")]
sal=sal_ac.append(sal_fl)
#sal = sal.append(sal_al)
salary=salary1.append(salary2)
salary=salary.append(salary3)
salary=salary.append(sal)
salary=salary.drop_duplicates(subset="Narration")
#dataframe.drop_duplicates(subset, keep, inplace, ignore_index)
UPI = data[data["Narration"].str.contains("UPI")]
NACH = data[data["Narration"].str.contains("NACH")]
ACH = data[data["Narration"].str.contains("ACH")]
NACH=NACH.append(ACH)

APP1672081644946102
hdfc-bank

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/VSK/Desktop/Bank statement/APP1672081644946102.pdf'

In [90]:
salary

,Transaction Date,Narration,Credit,Debit,Balance
63,04/05/20,EMBJZQIORQ47VN/RAZPEARLYSALARY,,"9,824.00","17,152.37"

In [91]:
NEFT

,Transaction Date,Narration,Credit,Debit,Balance
15,07/04/20,NEFT CR-BOFA0MM6205-ACC SOL PVT LTD-RAGHAVA KU...,"4,523.63",,"4,543.76"
25,21/04/20,NEFT CR-SBIN0000300-EMPLOYEE PROVIDENT FUND OR...,"59,145.00",,"59,145.00"
33,22/04/20,NEFT CR-BOFA0MM6205-ACC SOL PVT LTD-RAGHAVA KU...,"9,443.00",,"13,788.61"
42,29/04/20,NEFT CR-BOFA0MM6205-ACCENTURE SOLUTIONSPVT LTD...,"63,598.00",,"63,598.00"
85,29/05/20,NEFT CR-BOFA0MM6205-ACCENTURE SOLUTIONSPVT LTD...,"91,813.00",,"91,820.37"
95,01/06/20,NEFT CR-RATN0000999-GAK E SOLUTION PRIVATE LIM...,"12,000.00",,"75,120.37"
127,29/06/20,NEFT CR-BOFA0MM6205-ACCENTURE SOLUTIONSPVT LTD...,"65,732.00",,"66,143.37"
132,29/06/20,NEFT CR-RATN0000999-GAK E SOLUTION PRIVATE LIM...,"12,000.00",,"58,143.37"

In [92]:
com_table

,Date,Narration,Chq./Ref.No.,Value Dt,Withdrawal Amt.,Deposit Amt.,Closing Balance
1,02/04/20,IMPS-009311389162-RAGHAVA KUMAR A-UTIB-X,0000009311389162,02/04/20,"4,000.00",,"43,520.38"
2,,XXXXXXXXXX5588-TRANSFER,,,,,
3,02/04/20,M0IFFMUO14VLWZMYB4/AMAZONSELLER1,0000200936518498,02/04/20,"5,000.00",,"38,520.38"
4,02/04/20,IMPS-009313378869-RAGHAVA KUMAR A-UTIB-X,0000009313378869,02/04/20,"2,000.00",,"36,520.38"
5,,XXXXXXXXXX5588-TRANSFER,,,,,
6,02/04/20,ACH D- NORTHERN ARC CAPITAL-02424132,0000006425282015,02/04/20,"4,798.25",,"31,722.13"
7,02/04/20,EZE3TNQS1LAMRB/RAZPCASHXL,0000200936747677,02/04/20,"6,035.00",,"25,687.13"
8,03/04/20,IMPS-009411331801-RAGHAVA KUMAR A-UTIB-X,0000009411331801,03/04/20,"8,000.00",,"17,687.13"
9,,XXXXXXXXXX5588-TRANSFER,,,,,
10,03/04/20,ACH D- ICICI BANK LTD-LOANTP40HK5RVEHH,0000006476150744,03/04/20,"3,809.00",,"13,878.13"
11,03/04/20,RAZORPAY - EM42HAPN1YIBRR-847491,000000000000000,03/04/20,"10,058.00",,"3,820.13"
12,04/04/20,IMPS-009518327092-RAGHAVA KUMAR A-UTIB-X,0000009518327092,04/04/20,"3,800.00",,20.13
13,,XXXXXXXXXX5588-TRANSFER,,,,,
14,06/04/20,ACH D- TP ACH ICICI BANK-366205818,0000006662356762,06/04/20,"4,381.00",,"-4,360.87"
15,06/04/20,ACH D- TP ACH ICICI BANK-366205818,0000006662356762,06/04/20,,"4,381.00",20.13
16,07/04/20,NEFT CR-BOFA0MM6205-ACC SOL PVT LTD-RAGH,2046H4522GCK2844,07/04/20,,"4,523.63","4,543.76"
17,,AVA KUMAR ANGALU-2046H4522GCK2844,,,,,
18,07/04/20,EMI 59188491 CHQ S59188491120 042059188,0000000059188491,07/04/20,"7,733.00",,"-3,189.24"
19,,491,,,,,
20,07/04/20,EMI 59188491 CHQ S59188491120 042059188,0000000059188491,07/04/20,,"7,733.00","4,543.76"
21,,491,,,,,
22,08/04/20,EMI 59188491 CHQ S59188491120 042059188,000000000000000,08/04/20,"4,543.76",,0.00
23,,491-59188491,,,,,
24,13/04/20,RAZORPAY - CYHBPDZRXPNJLP-925149,000000000000000,13/04/20,"6,666.00",,"-6,666.00"
25,13/04/20,RAZORPAY - CYHBPDZRXPNJLP-925149,000000000000000,13/04/20,,"6,666.00",0.00
26,21/04/20,NEFT CR-SBIN0000300-EMPLOYEE PROVIDENT F,SBIN420112337473,21/04/20,,"59,145.00","59,145.00"
27,,UND ORGANIZATIO-A V V RAGHAVA KUMAR ANGA,,,,,
28,,LURI-SBIN420112337473,,,,,
29,21/04/20,IMPS-011216340722-RAGHAVA KUMAR A-UTIB-X,0000011216340722,21/04/20,"45,000.00",,"14,145.00"
30,,XXXXXXXXXX5588-TRANSFER,,,,,
31,21/04/20,KQQX654LBN6KHO62CY/PAYUMANAPPURAMFINANC,0000201126334850,21/04/20,"1,029.00",,"6,450.00"
32,21/04/20,KQQX654LBN62DPO3DY/PAYUMANAPPURAMFINANC,0000201126335944,21/04/20,792.39,,"5,657.61"
33,21/04/20,KQQX654LBNZKHOWQCY/PAYUMANAPPURAMFINANC,0000201126337207,21/04/20,"1,312.00",,"4,345.61"
34,22/04/20,NEFT CR-BOFA0MM6205-ACC SOL PVT LTD-RAGH,204LH3730KGJ0V30,22/04/20,,"9,443.00","13,788.61"
35,,AVA KUMAR ANGALU-204LH3730KGJ0V30,,,,,
36,22/04/20,IMPS-011307349136-RAGHAVA KUMAR A-UTIB-X,0000011307349136,22/04/20,"10,000.00",,"3,788.61"
37,,XXXXXXXXXX5588-TRANSFER,,,,,
38,24/04/20,RA REFUND POOL-59188491,0000004248068490,24/04/20,,"4,543.76","8,332.37"
39,25/04/20,IMPS-011608393298-RAGHAVA KUMAR A-UTIB-X,0000011608393298,25/04/20,"8,000.00",,332.37
40,,XXXXXXXXXX5588-TRANSFER,,,,,
41,27/04/20,.ACH DEBIT RETURN CHARGES 060420 060420-,MIR2011709436452,27/04/20,332.37,,0.00
42,,MIR2011709436452,,,,,
43,29/04/20,NEFT CR-BOFA0MM6205-ACCENTURE SOLUTIONS,0429202000051837,29/04/20,,"63,598.00","63,598.00"
44,,PVT LTD-ANGALURI RAGHAVA KUMAR-042920200,,,,,
45,,0051837 ACCENTURE SALARY APR20,,,,,
46,29/04/20,.ACH DEBIT RETURN CHARGES 060420 060420-,MIR2011912738025,29/04/20,257.63,,"63,340.37"
47,,MIR2011912738025,,,,,
48,29/04/20,SI FAIL DUE TO INSUFF BAL 080420-MIR2012,MIR2012013830302,29/04/20,236.00,,"63,104.37"
49,,013830302,,,,,
50,29/04/20,IMPS-012023111175-RAGHAVA KUMAR A-UTIB-X,0000012023111175,29/04/20,"17,000.00",,"46,104.37"
51,,XXXXXXXXXX5588-17000,,,,,
52,30/04/20,IMPS-012121003707-GAK E SOLUTION PRIVA-H,0000012121003707,30/04/20,,"10,000.00","56,104.37"
53,,DFC-XXXXXXXX9088-QCREDIT 242979,,,,,
54,01/05/20,IMPS-012211388784-RAGHAVA KUMAR A-UTIB-X,0000012211388784,01/05/20,"5,000.00",,"51,104.37"
55,,XXXXXXXXXX5588-TRANSFER,,,,,
56,01/05/20,IMPS-012211306480-RAGHAVA KUMAR A-UTIB-X,0000012211306480,01/05/20,500.00,,"50,604.37"
57,,XXXXXXXXXX5588-TRANSFER,,,,,
58,02/05/20,IMPS-012308318950-RAGHAVA KUMAR A-UTIB-X,0000012308318950,02/05/20,"6,670.00",,"43,934.37"
59,,XXXXXXXXXX5588-TRANSFER,,,,,
60,02/05/20,IMPS-012310346661-RAGHAVA KUMAR A-UTIB-X,0000012310346661,02/05/20,"3,900.00",,"40,034.37"
61,,XXXXXXXXXX5588-TRANSFER,,,,,
62,,XXXXXXXXXX5588-TRANSFER,,,,,
63,02/05/20,RAZORPAY - EM42HAPN1YIBRR-1100046,000000000000000,02/05/20,"10,058.00",,"26,976.37"
64,04/05/20,EMBJZQIORQ47VN/RAZPEARLYSALARY,0000201253138598,04/05/20,"9,824.00",,"17,152.37"
65,04/05/20,ACH D- LOANTAP CREDIT PRODU-LOANTP11MIHW,0000007742629279,04/05/20,"3,809.00",,"13,343.37"
66,04/05/20,IMPS-012513315674-RAGHAVA KUMAR A-UTIB-X,0000012513315674,04/05/20,"2,000.00",,"11,343.37"
67,,XXXXXXXXXX5588-TRANSFER,,,,,
68,05/05/20,50100296700987 NEW KIDS AC A SWASTHIKA,000000000000000,05/05/20,"1,000.00",,"10,343.37"
69,,S U/G RAGHAVA KU,,,,,
70,05/05/20,59188491-EMI RTN CHARGES-JANUARY- 010420,MIR2012519455218,05/05/20,236.00,,"10,107.37"
71,,-MIR2012519455218,,,,,
72,05/05/20,IMPS-012612363620-RAGHAVA KUMAR A-UTIB-X,0000012612363620,05/05/20,"1,000.00",,"9,107.37"
73,,XXXXXXXXXX5588-TRANSFER,,,,,
74,06/05/20,IMPS-012712303410-RAGHAVA KUMAR A-UTIB-X,0000012712303410,06/05/20,"1,000.00",,"8,107.37"
75,,XXXXXXXXXX5588-TRANSFER,,,,,
76,06/05/20,IMPS-012716343789-RAGHAVA KUMAR A-UTIB-X,0000012716343789,06/05/20,"3,000.00",,"5,107.37"
77,,XXXXXXXXXX5588-TRANSFER,,,,,
78,07/05/20,IMPS-012811311555-RAGHAVA KUMAR A-UTIB-X,0000012811311555,07/05/20,"1,000.00",,"4,107.37"
79,,XXXXXXXXXX5588-TRANSFER,,,,,
80,07/05/20,IMPS-012818392147-RAGHAVA KUMAR A-UTIB-X,0000012818392147,07/05/20,"1,000.00",,"3,107.37"
81,,XXXXXXXXXX5588-TRANSFER,,,,,
82,10/05/20,IMPS-013110314183-RAGHAVA KUMAR A-UTIB-X,0000013110314183,10/05/20,"1,000.00",,"2,107.37"
83,,XXXXXXXXXX5588-TRANSFER,,,,,
84,16/05/20,IMPS-013712379890-RAGHAVA KUMAR A-UTIB-X,0000013712379890,16/05/20,"2,100.00",,7.37
85,,XXXXXXXXXX5588-TRANSFER,,,,,
86,29/05/20,NEFT CR-BOFA0MM6205-ACCENTURE SOLUTIONS,0529202000168020,29/05/20,,"91,813.00","91,820.37"
87,,PVT LTD-ANGALURI RAGHAVA KUMAR-052920200,,,,,
88,,0168020 ACCENTURE SALARY MAY20,,,,,
89,29/05/20,IMPS-015010351352-RAGHAVA KUMAR A-UTIB-X,0000015010351352,29/05/20,"12,000.00",,"79,820.37"
90,,XXXXXXXXXX5588-TRANSFER,,,,,
91,29/05/20,IMPS-015012313908-RAGHAVA KUMAR A-UTIB-X,0000015012313908,29/05/20,"1,000.00",,"78,820.37"
92,,XXXXXXXXXX5588-TRANSFER,,,,,
93,,XXXXXXXXXX5588-TRANSFER,,,,,
94,30/05/20,IMPS-015111356339-RAGHAVA KUMAR A-UTIB-X,15111356339.0,30/05/20,"14,700.00",,"63,120.37"
95,,XXXXXXXXXX5588-TRANSFER,,,,,
96,01/06/20,NEFT CR-RATN0000999-GAK E SOLUTION PRIVA,123868061.0,01/06/20,,"12,000.00","75,120.37"
97,,TE LIMITED-RAGHAVAKUMAR AA VV-0001238680,,,,,
98,,61,,,,,
99,01/06/20,IMPS-015309326769-RAGHAVA KUMAR A-UTIB-X,15309326769.0,01/06/20,"7,200.00",,"67,920.37"
100,,XXXXXXXXXX5588-TRANSFER,,,,,
101,01/06/20,IMPS-015312374818-RAGHAVA KUMAR A-UTIB-X,15312374818.0,01/06/20,700.00,,"67,220.37"
102,,XXXXXXXXXX5588-TRANSFER,,,,,
103,01/06/20,IMPS-015316159536-RAGHAVA KUMAR A-UTIB-X,15316159536.0,01/06/20,"15,000.00",,"52,220.37"
104,,XXXXXXXXXX5588-15000,,,,,
105,02/06/20,IMPS-015411361513-RAGHAVA KUMAR A-UTIB-X,15411361513.0,02/06/20,"2,000.00",,"50,220.37"
106,,XXXXXXXXXX5588-TRANSFER,,,,,
107,02/06/20,IMPS-015411361742-RAGHAVA KUMAR A-UTIB-X,15411361742.0,02/06/20,"6,500.00",,"43,720.37"
108,,XXXXXXXXXX5588-TRANSFER,,,,,
109,03/06/20,IMPS-015510356852-RAGHAVA KUMAR A-UTIB-X,15510356852.0,03/06/20,"5,000.00",,"38,720.37"
110,,XXXXXXXXXX5588-TRANSFER,,,,,
111,03/06/20,ACH D- LOANTAP CREDIT PRODU-LOANTP28K3VK,8311668365.0,03/06/20,"3,809.00",,"34,911.37"
112,04/06/20,IMPS-015610320290-RAGHAVA KUMAR A-UTIB-X,15610320290.0,04/06/20,"7,000.00",,"27,911.37"
113,,XXXXXXXXXX5588-TRANSFER,,,,,
114,04/06/20,IMPS-015619135307-RAGHAVA KUMAR A-UTIB-X,15619135307.0,04/06/20,"15,000.00",,"12,911.37"
115,,XXXXXXXXXX5588-15000,,,,,
116,05/06/20,50100296700987 NEW KIDS AC A SWASTHIKA,0.0,05/06/20,"1,000.00",,"11,911.37"
117,,S U/G RAGHAVA KU,,,,,
118,06/06/20,EMI 59188491 CHQ S591884910221 06205918,0.0,06/06/20,"7,733.00",,"4,178.37"
119,,8491,,,,,
120,06/06/20,IMPS-015809198258-RAGHAVA KUMAR A-UTIB-X,15809198258.0,06/06/20,"4,000.00",,178.37
121,,XXXXXXXXXX5588-4000,,,,,
122,10/06/20,RA REFUND POOL-59188491,6103218574.0,10/06/20,,"7,733.00","7,911.37"
123,10/06/20,IMPS-016213308496-RAGHAVA KUMAR A-UTIB-X,16213308496.0,10/06/20,"3,500.00",,"4,411.37"
124,10/06/20,IMPS-016213309815-RAGHAVA KUMAR A-UTIB-X,0000016213309815,10/06/20,"1,500.00",,"2,911.37"
125,,XXXXXXXXXX5588-TRANSFER,,,,,
126,20/06/20,IMPS-017219353812-RAGHAVA KUMAR A-UTIB-X,0000017219353812,20/06/20,"2,500.00",,411.37
127,,XXXXXXXXXX5588-TRANSFER,,,,,
128,29/06/20,NEFT CR-BOFA0MM6205-ACCENTURE SOLUTIONS,0626202000101951,29/06/20,,"65,732.00","66,143.37"
129,,PVT LTD-ANGALURI RAGHAVA KUMAR-062620200,,,,,
130,,0101951 ACCENTURE SALARY JUN20,,,,,
131,29/06/20,IMPS-018111300626-RAGHAVA KUMAR A-UTIB-X,0000018111300626,29/06/20,"20,000.00",,"46,143.37"
132,,XXXXXXXXXX5588-TRANSFER,,,,,
133,29/06/20,NEFT CR-RATN0000999-GAK E SOLUTION PRIVA,0000000127045462,29/06/20,,"12,000.00","58,143.37"
134,,TE LIMITED-RAGHAVAKUMAR AA VV-0001270454,,,,,
135,,62,,,,,
136,29/06/20,SHDF8944420980/CITIBANK CREDIT CARD,0000201818706852,29/06/20,"52,641.00",,"5,502.37"
137,29/06/20,IMPS-018117398314-RAGHAVA KUMAR A-UTIB-X,0000018117398314,29/06/20,"5,000.00",,502.37
138,,XXXXXXXXXX5588-TRANSFER,,,,,
139,01/07/20,CREDIT INTEREST CAPITALISED,000000000000000,30/06/20,,67.00,569.37
140,01/07/20,IMPS-018314343740-A A V V RAGHAVA KUMA-H,0000018314343740,01/07/20,,"3,000.00","3,569.37"
141,,DFC-XXXXXXXXXXX5588-,,,,,
142,01/07/20,IB FUNDS TRANSFER CR-50100296700987-A SW,BM01830208008907,01/07/20,,600.00,"4,169.37"
143,,ASTHIKA S U/G RAGHAVA KUMAR,,,,,
144,03/07/20,IMPS-018510952707-NAGAPRATAPA REDDY NI-H,0000018510952707,03/07/20,,"30,000.00","34,169.37"
145,,DFC-XXXXXXXX5024-FRIENDS,,,,,
146,03/07/20,IMPS-018510315451-RAGHAVA KUMAR A-UTIB-X,0000018510315451,03/07/20,"20,000.00",,"14,169.37"
147,,XXXXXXXXXX5588-TRANSFER,,,,,
148,03/07/20,IMPS-018511327897-RAGHAVA KUMAR A-UTIB-X,0000018511327897,03/07/20,"9,000.00",,"5,169.37"
149,,XXXXXXXXXX5588-TRANSFER,,,,,
150,03/07/20,ACH D- LOANTAP CREDIT PRODU-LOANTP83S2XQ,0000009046734185,03/07/20,"3,809.00",,"1,360.37"
151,04/07/20,IMPS-018613314054-RAGHAVA KUMAR A-UTIB-X,0000018613314054,04/07/20,"1,000.00",,360.37
152,,XXXXXXXXXX5588-TRANSFER,,,,,
153,,STATEMENT SUMMARY :-,,,,,